### ISSUE TITLE
Unable to show progress in WebView

### ISSUE THREAD

**Issue by mochadwi** [SIARAY/DownloadManagerPlus#12]
`DownloadManager#showProgress` doesn't shown if I tried to download image from WebView (I implemented this library inside JsInterface)

**Comment by SIARAY** [comment]
> `DownloadManager#showProgress` doesn't shown if I tried to download image from WebView (I implemented this library inside JsInterface)

This method (showProgress) does not display any progress, it only updates the download listener to display the download details.
You need to implement a progressView and update its values ​​in the download listener.

**Comment by mochadwi** [comment]
Okay, that's explained everything. Thanks!
