### ISSUE TITLE
Unable to save files into apps data directory.

### ISSUE THREAD

**Issue by Pradeepkumar2091** [SIARAY/DownloadManagerPlus#16]
Hi,
I want to download video file in apps`data directory (i.e **data/user/0/my.package.name/files/8950a6cd-a413-4cc2-94be-18b4d964dc49.mp4**)

But when i start download then a log is showing that **DownloadDirectory is not valid, downloaded file will be save in default directory.** and the files is downloaded into the Download directory.

Please help me.

**Comment by SIARAY** [comment]
Hi,
I think this is only possible on TargetApi 28 and below

**Comment by SIARAY** [comment]
> Hi,
> I want to download video file in apps`data directory (i.e **data/user/0/my.package.name/files/8950a6cd-a413-4cc2-94be-18b4d964dc49.mp4**)
> 
> But when i start download then a log is showing that **DownloadDirectory is not valid, downloaded file will be save in default directory.** and the files is downloaded into the Download directory.
> 
> Please help me.

Hi,
I think this is only possible on TargetApi 28 and below
