### ISSUE TITLE
Download failed after 99% done!

### ISSUE THREAD

**Issue by HiddenPirates** [SIARAY/DownloadManagerPlus#17]
Download failed after 99% done! Showing error message "ERROR_CANNOT_RESUME"

               DownloadListener listener = new DownloadListener() {

                    @Override
                    public void onComplete(int totalBytes) {
                        Log.d("VVVVV", "complete");
                    }

                    @Override
                    public void onPause(int percent, DownloadReason reason, int totalBytes, int downloadedBytes) {
                        Log.d("VVVVV", "pause");
                    }

                    @Override
                    public void onPending(int percent, int totalBytes, int downloadedBytes) {

                        Log.d("VVVVV", "pending");
                    }

                    @Override
                    public void onFail(int percent, DownloadReason reason, int totalBytes, int downloadedBytes) {

                        Log.d("VVVVV", "fail");
                        Log.d("VVVVV", reason.toString());
                    }

                    @Override
                    public void onCancel(int totalBytes, int downloadedBytes) {

                        Log.d("VVVVV", "cancel");
                    }

                    @Override
                    public void onRunning(int percent, int totalBytes, int downloadedBytes, float downloadSpeed) {

                        Log.d("VVVVV", "running");
                        Log.d("VVVVV", String.valueOf(percent));
                    }
                };

                Downloader downloader = Downloader.getInstance(context)
                        .setUrl(fileDownLink)
                        .setListener(listener)
                        .setToken(new Random().nextInt()+"t")
                        .setAllowedOverRoaming(true)
                        .setAllowedOverMetered(true) //Api 16 and higher
                        .setVisibleInDownloadsUi(true)
                        .setDestinationDir(Environment.DIRECTORY_DOWNLOADS, fileTitle)
                        .setNotificationTitle(fileTitle)
                        .setDescription("Download in progress")
                        .setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE)
                        .setAllowedNetworkTypes(DownloadManager.Request.NETWORK_WIFI | DownloadManager.Request.NETWORK_MOBILE)
                        .setKeptAllDownload(false);

                downloader.start();

**Comment by SIARAY** [comment]
> Download failed after 99% done! Showing error message "ERROR_CANNOT_RESUME"
> 
> ```
>            DownloadListener listener = new DownloadListener() {
> 
>                 @Override
>                 public void onComplete(int totalBytes) {
>                     Log.d("VVVVV", "complete");
>                 }
> 
>                 @Override
>                 public void onPause(int percent, DownloadReason reason, int totalBytes, int downloadedBytes) {
>                     Log.d("VVVVV", "pause");
>                 }
> 
>                 @Override
>                 public void onPending(int percent, int totalBytes, int downloadedBytes) {
> 
>                     Log.d("VVVVV", "pending");
>                 }
> 
>                 @Override
>                 public void onFail(int percent, DownloadReason reason, int totalBytes, int downloadedBytes) {
> 
>                     Log.d("VVVVV", "fail");
>                     Log.d("VVVVV", reason.toString());
>                 }
> 
>                 @Override
>                 public void onCancel(int totalBytes, int downloadedBytes) {
> 
>                     Log.d("VVVVV", "cancel");
>                 }
> 
>                 @Override
>                 public void onRunning(int percent, int totalBytes, int downloadedBytes, float downloadSpeed) {
> 
>                     Log.d("VVVVV", "running");
>                     Log.d("VVVVV", String.valueOf(percent));
>                 }
>             };
> 
>             Downloader downloader = Downloader.getInstance(context)
>                     .setUrl(fileDownLink)
>                     .setListener(listener)
>                     .setToken(new Random().nextInt()+"t")
>                     .setAllowedOverRoaming(true)
>                     .setAllowedOverMetered(true) //Api 16 and higher
>                     .setVisibleInDownloadsUi(true)
>                     .setDestinationDir(Environment.DIRECTORY_DOWNLOADS, fileTitle)
>                     .setNotificationTitle(fileTitle)
>                     .setDescription("Download in progress")
>                     .setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE)
>                     .setAllowedNetworkTypes(DownloadManager.Request.NETWORK_WIFI | DownloadManager.Request.NETWORK_MOBILE)
>                     .setKeptAllDownload(false);
> 
>             downloader.start();
> ```

Can you send the download link?
