### ISSUE TITLE
Error open downloaded in android N

### ISSUE THREAD

**Issue by cahyofendhi** [SIARAY/DownloadManagerPlus#2]
error when running in android N or above
after download complete `force close` 

```
Process: eserviceapp.pkt.com.pkt_eservice, PID: 3427
    java.lang.RuntimeException: Unable to start receiver com.app.service.DownloadBroadcastReceiver: java.lang.SecurityException: COLUMN_LOCAL_FILENAME is deprecated; use ContentResolver.openFileDescriptor() instead
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
```

**Comment by SIARAY** [comment]
> error when running in android N or above
> after download complete `force close`
> 
> ```
> Process: eserviceapp.pkt.com.pkt_eservice, PID: 3427
>     java.lang.RuntimeException: Unable to start receiver com.app.service.DownloadBroadcastReceiver: java.lang.SecurityException: COLUMN_LOCAL_FILENAME is deprecated; use ContentResolver.openFileDescriptor() instead
>         at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
>         at android.app.ActivityThread.-wrap17(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6541)
> ```

Please ,check new version(1.2.6)
