### ISSUE TITLE
How to add custom download path ?

### ISSUE THREAD

**Issue by ptatiya** [SIARAY/DownloadManagerPlus#20]
Can we add custom download path in this library ? please let me know 

for example : getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS);

how to add this download path ? please let me know.

**Comment by SIARAY** [comment]
Please check sample
You can save your downloads in the download folder by the following line
` .setDestinationDir(Storage.DIRECTORY_DOWNLOADS, fileName)`

But the custom directory just supports in targetApi 28 and lower by the following line
`.setCustomDestinationDir(downloadPath, fileName)//TargetApi 28 and lower`
