### ISSUE TITLE
 @Override             public void onComplete(int totalBytes) {} call everytime after download

### ISSUE THREAD

**Issue by birjubhatt** [SIARAY/DownloadManagerPlus#3]
hi i am working in my application using your library 
my problame is after suacess download your library always call this onComplete method

why need to point every time i already know that my file is downloaded...
its work like as infinite 

please solve this

**Comment by SIARAY** [comment]
Hi,
Yes that's right.
We will need to call this method to display the details of the download that has been completed.
If you were having trouble displaying the message when the download was completed and every time this message is displayed,
I recommend, keep the latest download status and display the message when the status is changed from "RUNNING" to "SUCCESSFUL".
I will try to resolve this problem in future versions.
