### ISSUE TITLE
Crashing on android Q

### ISSUE THREAD

**Issue by SanjayKushwah0601** [SIARAY/DownloadManagerPlus#5]
It is getting crashed if set my targetSdkVersion =29. Could you please resolve this issue.

**Comment by SIARAY** [comment]
Hi,
Thanks for your reporting,
I will check it,
And I will fix the problem soon.

**Comment by SIARAY** [comment]
> It is getting crashed if set my targetSdkVersion =29. Could you please resolve this issue.

When did you encounter an error?

**Comment by SIARAY** [comment]
This problem fixed 
[https://github.com/SIARAY/DownloadManagerPlus/commit/3712d2b4c2e0c153c34ad8aed8de417a6223b7f4](This update)
