### ISSUE TITLE
Realtime populating data with RecyclerView

### ISSUE THREAD

**Issue by nana-desu** [SIARAY/DownloadManagerPlus#7]
I have tried to get data by using Downloader.getDownloadsList(this) and add to adapter as Recycler, but i don't know where to trigger the update. Should i use DownloadListener from instance? or maybe can you provide any specific example to implement them?
Thank you

**Comment by SIARAY** [comment]
> I have tried to get data by using Downloader.getDownloadsList(this) and add to adapter as Recycler, but i don't know where to trigger the update. Should i use DownloadListener from instance? or maybe can you provide any specific example to implement them?
> Thank you

Hi,
This can be done.
I'll try to set an example soon.

**Comment by SIARAY** [comment]
Sample code inserted.
DownloadListAdapter
