### ISSUE TITLE
App Crashes in Sdk 29 

### ISSUE THREAD

**Issue by nashbangalore** [SIARAY/DownloadManagerPlus#8]
The App Crashes in Sdk 29 

at ir.siaray.downloadmanagerplus.classes.Downloader.isThereAnError (Downloader.java:222)
at ir.siaray.downloadmanagerplus.classes.Downloader.start (Downloader.java:170)

**Comment by SIARAY** [comment]
> The App Crashes in Sdk 29
> 
> at ir.siaray.downloadmanagerplus.classes.Downloader.isThereAnError (Downloader.java:222)
> at ir.siaray.downloadmanagerplus.classes.Downloader.start (Downloader.java:170)

Have you tested the latest version (1.4.0)?

**Comment by nashbangalore** [comment]
Yes

**Comment by SIARAY** [comment]
> Yes

Please write here the code you used to download. I tested the app on the emulator but saw no error
